# Generated by Django 6.0 on 2026-01-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]
    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="token",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="token"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="users/avatars/", verbose_name="Аватар"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="country",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Страна"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Телефон"
            ),
        ),
    ]
