# Generated by Django 6.0 on 2026-01-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogs",
            name="content",
            field=models.TextField(blank=True, null=True, verbose_name="Текст"),
        ),
        migrations.AlterField(
            model_name="blogs",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Заголовок"),
        ),
    ]
