# Generated by Django 6.0 on 2025-12-19 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_category_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(choices=[('food', 'еда'), ('chemical', 'бытовая химия'), ('pet', 'для питомцев')], on_delete=django.db.models.deletion.CASCADE, to='catalog.category'),
        ),
    ]
