# Generated by Django 6.0 on 2025-12-23 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                choices=[
                    ("food", "еда"),
                    ("chemical", "бытовая химия"),
                    ("pet", "для питомцев"),
                ],
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="catalog.category",
            ),
        ),
    ]
