# Generated by Django 6.0 on 2025-12-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_remove_product_images_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="product/image",
                verbose_name="Изображение",
            ),
        ),
    ]
