# Generated by Django 6.0 on 2025-12-26 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_alter_product_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AlterModelTable(
            name="product",
            table="django_project",
        ),
    ]
