# Generated by Django 6.0 on 2026-01-14 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_alter_category_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="product",
            table=None,
        ),
    ]
