# Generated by Django 6.0 on 2026-01-24 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_product_is_available"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_available",
        ),
    ]
