# Generated by Django 6.0 on 2026-01-29 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_alter_product_options_product_owner_product_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "permissions": [
                    ("can_unpublish_product", "Право на отмену публикации товара"),
                    ("can_delete_product", "Право на удаление продукта"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
